pub const precision_factor = 10_000_000

// "st-receipt"
pub const receipt_token_name = #"73742d72656365697074"

// "st-identifier"
pub const identifier_token_name = "73742D6964656E746966696572"

// "STO"
pub const st_oracle_asset_name = #"53544f"

// "STP"
pub const st_pparams_asset_name = #"535450"

// staterites (sUSD subnuits (1_000_000 staterites == 1 sUSD))
pub const st_stable_asset_name = #"73746174657269746573"
